language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
- julia build_tarballs.jl
deploy:
  provider: releases
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: JuliaIO/LibVPXBuilder
  api-key:
    secure: aAqIwL8rX+eyVS63mHWI6B+ZIIyv9mDcxmGpl8SBjqwJ0Qi9/lLaDXgI94sY7FuOPWiUBPeFh2c/0b89MJwQUURMoTJ7hGkovVy8XRcVgoiSyRc6wu9PwVUAWRFE2S/DtKKqM4mUu3sYb8Zru2fK3Cos7C3/YOOpeVmj9PwMtgiepNxlAnu9jR188/k9JY7yrQWqDC8IB99yoRxUBUlM6QhzwgcDTfIl3DBDqr/aBQO/dEzDB9ejB80DSoBwioQDqewTxAdvy87baKKU0opwh0W+stzuS4ZrYvZg88jNFDhQVR+uPgKoEBx47CBIyiMYTfPCEZFvH259suhPPJTgYA1uNovWTwZOfrH+Pwvd4d50eLO2QxcUfwIJITUFTFMb/b/rh+vg8g7mJcuYRqLsKMIn6/NDPRmCvi9dhXMWFBayn1F8ALidO8xXvSxuViZS8PnxleTq3eD8XESXjJWPxvGE5VrVj0NnPayAsbLYohKmp/Odg4YODRDammMPs9e5JLS6BVu8P6kpiQxON9epM+lI7CU+SiICXK7vZyVZQo5cUUhv6o7WwKoJOOOHCkfwOEoBgPvvoFg5E/mvpe8djhNzJHEv59zAtMF0foTj0PCy/Rm7fLydp9KREFpsrpOOxnrR9LWtbV7YoSCp/6Hfm4M5JCa0LlJfpxu3h6zD+HM=
